# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateupsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='mateupsite.Attribute'),
        ),
    ]
